### ISSUE TITLE
[SUGGESTION] Support for even moar mods

### ISSUE THREAD

**Issue by Sunconure11** [supermassimo/DynamicTrees-ExC#1]
https://www.curseforge.com/minecraft/mc-mods/plants

https://www.curseforge.com/minecraft/mc-mods/vampirism-become-a-vampire

https://www.curseforge.com/minecraft/mc-mods/abyssalcraft

https://www.curseforge.com/minecraft/mc-mods/environs

https://www.curseforge.com/minecraft/mc-mods/redwoods

https://www.curseforge.com/minecraft/mc-mods/novam-terram

https://www.curseforge.com/minecraft/mc-mods/auxiliary-biomes

https://www.curseforge.com/minecraft/mc-mods/wizardry-mod

https://www.curseforge.com/minecraft/mc-mods/natures-aura

https://www.curseforge.com/minecraft/mc-mods/gaia-dimension

Some of these might require their own addons.

**Comment by breach-candy** [comment]
BYG?

https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go

**Comment by supermassimo** [comment]
Moved mod support suggestions to https://github.com/supermassimo/DynamicTrees-ExC/issues/41
