### ISSUE TITLE
[Request/suggestion] PMP / Totemic

### ISSUE THREAD

**Issue by pimalel233** [supermassimo/DynamicTrees-ExC#13]
Hi, great mod!
Would you consider adding support to two of the following mods?
Totemic - https://www.curseforge.com/minecraft/mc-mods/totemic - it has one tree
Plant Mega Pack - https://web.archive.org/web/20190201061706/10paksmods.net/ - I think it has around 55 trees, just normal trees, no big ones

Thanks for consideration!

**Comment by B-Wither** [comment]
About PMP, if Dynamic Trees and PMP are installed at the same time, there will be a problem in Epiphyte generation.
Fixing this seems pretty difficult...

**Comment by supermassimo** [comment]
I can do totemic, plant mega pack is a bit too much for me

**Comment by supermassimo** [comment]
totemic done :) https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-totemic

**Comment by pimalel233** [comment]
@supermassimo thanks and appreciated, still hoping for pmp that it might happen in the future or so :)
