### ISSUE TITLE
[Request] Project Vibrant Journeys, Abyssalcraft, Defiled Lands

### ISSUE THREAD

**Issue by lamoyrl90** [supermassimo/DynamicTrees-ExC#14]
Heyooo, I'd like to submit my humble request for Project Vibrant Journeys and Abyssalcraft integration. Most of the trees for PVJ are pretty straightforward - Aspens are tall birch, Maple are tall oak, and Pine are basically spruce. Willows, palms and Mangroves may be trickier, but inspiration for willows could be taken from BoP or your own Natura compat mods. Palms exist in BoP compat already, so they could just be copied from those settings with the addition of coconuts hanging like apples from apple oaks. Mangroves, however, may be a bit more complicated.

 Abyssalcraft only has two trees and they're identical save for their color.

 Defiled Lands' trees are pretty much straight up copies of dying oaks from BoP.

**Comment by supermassimo** [comment]
Moved mod support suggestions to https://github.com/supermassimo/DynamicTrees-ExC/issues/41
