### ISSUE TITLE
[Suggestion] ExtraTrees Compat

### ISSUE THREAD

**Issue by leonbaronick** [supermassimo/DynamicTrees-ExC#15]
ExtraTrees is part of [Binnie's Mods](https://www.curseforge.com/minecraft/mc-mods/binnies-mods), an addon for the forestry mod.

It adds a whole bunch of trees (the curseforge page states 96 new species) and it would be awesome to have dynamic trees support for them, although it's probably a huge amount of work.

**Comment by supermassimo** [comment]
I think ill pass for the time being! 96 trees is way too many for my sanity haha
