### ISSUE TITLE
[Suggestion] Advent of Ascension Trees 

### ISSUE THREAD

**Issue by zero-breaker** [supermassimo/DynamicTrees-ExC#16]
[Advent of Ascension](https://www.curseforge.com/minecraft/mc-mods/advent-of-ascension-nevermine) adds a wide variety of trees that generate in the two dozens of dimensions.

Some of them might be difficult to work with i.e. Lelyetia's upside-down trees and Lunalus' trees with non-connected leaves, but it'd be nice to see support for these trees.

**Comment by supermassimo** [comment]
For the time being ill pass, those are way too many trees to work on even if they are all simple

**Comment by supermassimo** [comment]
Moved mod support suggestions to https://github.com/supermassimo/DynamicTrees-ExC/issues/41
