### ISSUE TITLE
OTG Compat? (Biome Bundle etc)

### ISSUE THREAD

**Issue by MagmaSlime123** [supermassimo/DynamicTrees-ExC#21]
https://www.curseforge.com/minecraft/mc-mods/open-terrain-generator
https://minecraft.curseforge.com/projects/biome-bundle
https://www.curseforge.com/minecraft/mc-mods/vanilla-vistas
https://minecraft.curseforge.com/projects/dregora
https://www.curseforge.com/minecraft/mc-mods/travelers-dream
https://www.curseforge.com/minecraft/mc-mods/thaumic-travelers-dream

**Comment by supermassimo** [comment]
Unfortunately the open terrain generator seems to be way too complex for me to be able to reliably replace all trees with dynamic ones. The customization factor makes it impossible to design trees for all possibilities as far as i'm aware.
