### ISSUE TITLE
[YES, ONE MORE SUGGESTION] The Erebus

### ISSUE THREAD

**Issue by ghost** [supermassimo/DynamicTrees-ExC#23]
https://www.curseforge.com/minecraft/mc-mods/the-erebus

Dude, you're doing an incredible job. Creating compatibility with almost all mods with trees is a lot of work. Thanks for these great mods! I look forward to mods for Twilight Forest, Defiled Lands and Erebus.

**Comment by supermassimo** [comment]
Moved mod support suggestions to https://github.com/supermassimo/DynamicTrees-ExC/issues/41
