### ISSUE TITLE
Getting a crash when entering the Twilight Forest, with the newly released Twilight Forest Dynamic Trees Compat. mod.

### ISSUE THREAD

**Issue by MagmaSlime123** [supermassimo/DynamicTrees-ExC#27]
Getting a crash when entering the dimension with this installed.

https://pastebin.com/d8hB4C4h

**Comment by democat3457** [comment]
Crash appears to have nothing associated with Dynamic Trees Compat. Looks like in the MultiMob config, a spawn entry has an additional rarity of 0, when it should be -1.

EDIT: just noticed https://github.com/Daveyx0/MultiMob/issues/37 with more information while searching on the mod repo.

**Comment by MagmaSlime123** [comment]
Oh.
