### ISSUE TITLE
Mod idea: Dynamic Mushrooms

### ISSUE THREAD

**Issue by MagmaSlime123** [supermassimo/DynamicTrees-ExC#28]
Simply put it, just makes all mushrooms act like dynamic trees would. Could also have compat. with mods that add their own mushroom types too. Dynamic Trees Twilight Forest could also integrate with this to make the giant mushrooms in the Twilight Forest dynamic.

**Comment by supermassimo** [comment]
This will be implemented as a feature in Dynamic Trees Plus
