### ISSUE TITLE
[BUG] [Aether: Legacy] Golden Oak trees don't drop Golden Amber

### ISSUE THREAD

**Issue by democat3457** [supermassimo/DynamicTrees-ExC#32]
When hitting dynamic golden oak trees with gravitite, zanite, or valkyrie axes, they don't drop golden amber.
Relevant lines from Aether: Legacy repository: https://gitea.gildedgames.com/GildedGames/The-Aether/src/branch/1.12.2/src/main/java/com/legacy/aether/blocks/natural/BlockAetherLog.java#L88-L96

**Comment by supermassimo** [comment]
totally forgot this was a feature! will fix soon :)

**Comment by supermassimo** [comment]
Fixed in [1.0.4](https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-the-aether-legacy/files/3023263)
