### ISSUE TITLE
[Suggestion] Compatability for The Aurorian

### ISSUE THREAD

**Issue by Azuriuz** [supermassimo/DynamicTrees-ExC#37]
It's a relatively new dimension mod, still in beta, but as you have done, or are doing, just about every other dimension mod (in my modpack or otherwise) I figured I'd suggest it as it's a rather lovely up and coming dimension that I'd love to see more support for. 
_And it's the only dimension in my pack that doesn't have dynamic trees support done, or in the works._
It only has 2 trees populating the dimension as well, so it shouldn't be too terribly huge a project, I hope!

https://www.curseforge.com/minecraft/mc-mods/the-aurorian

**Comment by supermassimo** [comment]
Moved mod support suggestions to https://github.com/supermassimo/DynamicTrees-ExC/issues/41
