### ISSUE TITLE
slimes not spawning from slime islands in overworld

### ISSUE THREAD

**Issue by straef** [supermassimo/DynamicTrees-ExC#38]
![image](https://user-images.githubusercontent.com/20950411/91085148-9ca3c600-e612-11ea-851a-1ef76aa8d1ad.png)

using the mods shown, and only those mods: slimes do not spawn on slime islands in the overworld.

by removing dynamic trees for tinker's construct slimes will spawn on newly generated slime islands. already generated islands will not ever spawn slimes.

**Comment by supermassimo** [comment]
Fixed in [1.2.1](https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-tinkers-construct/files/3045054)
