### ISSUE TITLE
[Suggestion] Compatibility for Redwoods

### ISSUE THREAD

**Issue by dracoattila** [supermassimo/DynamicTrees-ExC#39]
https://www.curseforge.com/minecraft/mc-mods/redwoods
It would be awesome if this mod could get a dynamic tree addon. It's a port of the old Extrabiomes XL mod most memorible woods.

**Comment by supermassimo** [comment]
Duplicate of https://github.com/supermassimo/DynamicTrees-ExC/issues/1
