### ISSUE TITLE
ExC/IC2 rubber tree client crash

### ISSUE THREAD

**Issue by Sarous** [supermassimo/DynamicTrees-ExC#4]
Client crash when attempting to collect resin from ExC rubber tree. Re-tested to confirm with only IC2, Dynamic Trees, and DT ExC.

<details>
  <summary>Crash Log from re-test</summary>
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 4/22/20 2:20 AM
Description: Unexpected error

java.lang.NoClassDefFoundError: reborncore/common/util/WorldUtils
	at maxhyper.dynamictreesexc.blocks.BlockDynamicBranchRubberIC.func_180639_a(BlockDynamicBranchRubberIC.java:104)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:423)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: reborncore.common.util.WorldUtils
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at maxhyper.dynamictreesexc.blocks.BlockDynamicBranchRubberIC.func_180639_a(BlockDynamicBranchRubberIC.java:104)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:423)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Sarous'/108, l='MpServer', x=275.46, y=64.00, z=157.11]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (112,64,252), Chunk: (at 0,4,12 in 7,15; contains blocks 112,0,240 to 127,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 866688 game time, 866688 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 33 total; [EntitySkeleton['Skeleton'/136, l='MpServer', x=342.71, y=18.00, z=107.50], EntitySpider['Spider'/328, l='MpServer', x=292.50, y=21.00, z=174.50], EntitySkeleton['Skeleton'/137, l='MpServer', x=352.63, y=16.00, z=84.50], EntitySkeleton['Skeleton'/201, l='MpServer', x=331.50, y=20.00, z=166.50], EntityCreeper['Creeper'/138, l='MpServer', x=332.50, y=19.00, z=126.50], EntitySkeleton['Skeleton'/202, l='MpServer', x=332.50, y=20.00, z=166.50], EntityZombie['Zombie'/139, l='MpServer', x=326.42, y=29.00, z=233.06], EntityZombie['Zombie'/140, l='MpServer', x=326.59, y=29.00, z=232.24], EntityItem['item.item.rottenFlesh'/77, l='MpServer', x=281.24, y=62.94, z=116.62], EntitySkeleton['Skeleton'/333, l='MpServer', x=345.50, y=11.00, z=89.50], EntityXPOrb['Experience Orb'/78, l='MpServer', x=281.53, y=62.00, z=113.47], EntityCreeper['Creeper'/334, l='MpServer', x=342.50, y=11.00, z=92.50], EntityXPOrb['Experience Orb'/79, l='MpServer', x=280.89, y=62.94, z=116.59], EntityZombie['Zombie'/335, l='MpServer', x=344.50, y=11.00, z=87.50], EntityXPOrb['Experience Orb'/80, l='MpServer', x=277.61, y=63.50, z=116.72], EntityZombie['Zombie'/336, l='MpServer', x=344.50, y=11.00, z=85.50], EntityXPOrb['Experience Orb'/81, l='MpServer', x=284.29, y=63.00, z=116.64], EntityXPOrb['Experience Orb'/82, l='MpServer', x=283.59, y=63.00, z=117.53], EntityXPOrb['Experience Orb'/83, l='MpServer', x=285.42, y=63.00, z=117.75], EntityBat['Bat'/277, l='MpServer', x=233.52, y=23.69, z=80.15], EntitySkeleton['Skeleton'/88, l='MpServer', x=291.50, y=24.00, z=188.50], EntityXPOrb['Experience Orb'/153, l='MpServer', x=385.01, y=69.00, z=154.16], EntityPlayerSP['Sarous'/108, l='MpServer', x=275.46, y=64.00, z=157.11], EntityXPOrb['Experience Orb'/154, l='MpServer', x=384.97, y=69.00, z=154.75], EntityXPOrb['Experience Orb'/155, l='MpServer', x=385.49, y=69.00, z=152.45], EntityZombie['Zombie'/225, l='MpServer', x=317.50, y=19.00, z=86.50], EntityZombie['Zombie'/226, l='MpServer', x=315.50, y=19.00, z=90.50], EntityBat['Bat'/228, l='MpServer', x=349.69, y=17.74, z=80.24], EntityCreeper['Creeper'/101, l='MpServer', x=311.50, y=18.00, z=77.50], EntityCreeper['Creeper'/102, l='MpServer', x=319.20, y=59.00, z=155.56], EntitySkeleton['Skeleton'/307, l='MpServer', x=244.50, y=67.00, z=156.50], EntitySkeleton['Skeleton'/57, l='MpServer', x=205.49, y=64.00, z=118.67], EntityItem['item.item.rottenFlesh'/63, l='MpServer', x=238.37, y=71.00, z=114.64]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1466809424 bytes (1398 MB) / 2415919104 bytes (2304 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID              | Version       | Source                              | Signature                                |
	|:------ |:--------------- |:------------- |:----------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft       | 1.12.2        | minecraft.jar                       | None                                     |
	| LCHIJA | mcp             | 9.42          | minecraft.jar                       | None                                     |
	| LCHIJA | FML             | 8.0.99.99     | forge-1.12.2-14.23.5.2847.jar       | None                                     |
	| LCHIJA | forge           | 14.23.5.2847  | forge-1.12.2-14.23.5.2847.jar       | None                                     |
	| LCHIJA | dynamictrees    | 1.12.2-0.9.7  | DynamicTrees-1.12.2-0.9.7.jar       | None                                     |
	| LCHIJA | dynamictreesexc | 0.11          | dynamictreesExC-0.11.jar            | None                                     |
	| LCHIJA | ic2             | 2.8.197-ex112 | industrialcraft-2-2.8.197-ex112.jar | de041f9f6187debbc77034a344134053277aa3b0 |

	Loaded coremods (and transformers): 
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics 620 GL version 4.5.0 - Build 24.20.100.6286, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-8130U CPU @ 2.20GHz
</details>

**Comment by Harleyoc1** [comment]
It's some sort of problem with the code looking for Tech Reborn when harvesting from the IC2 rubber tree. It works when installing Tech Reborn if you still want to use the mod before this crash is fixed.

**Comment by Harleyoc1** [comment]
Having looked into the code, it looks to be a simple fix. Right now, the code is defining the resin ItemStack before checking which mods are installed. Therefore it's trying to drop the resin item from Tech Reborn, which causes the game to crash as the mod isn't installed.

**Comment by supermassimo** [comment]
Harleyoc1 is right, I just havent had the time to fix it. Will be fixed in the next update.

**Comment by supermassimo** [comment]
Fixed in [DT-IC2 1.0](https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-integrated-dynamics/files/2968305)
