### ISSUE TITLE
forestry addon for dynamic trees doesnt respect forestry blacklisting

### ISSUE THREAD

**Issue by xemnes** [supermassimo/DynamicTrees-ExC#47]
dynamic trees forestry overrides the aboriculture config file that allows tree blacklisting on a per biome basis. 
is it possible for it to respect that config as i want to disable some trees spawning in certain biomes, like baobab in plains biomes.

**Comment by supermassimo** [comment]
Fixed in [1.0.5](https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-forestry/files)
