### ISSUE TITLE
Crash with one of these mods and the mod "ArchitectureCraft - TridentMC version"

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [supermassimo/DynamicTrees-ExC#53]
* dynamictreesQuark-1.12.2-1.0.5 to dynamictreesQuark-1.12.2-1.0.6 - minor fixes. (Reverted due to issues with texture mimic api causing crash)

* dynamictreesTConstruct-1.12.2-1.2.4 to dynamictreesTConstruct-1.12.2-1.2.5 - minor fixes (Reverted due to issues with texture mimic api causing crash)
[crash-2020-11-01_17.54.40-client.txt](https://github.com/supermassimo/DynamicTrees-ExC/files/5472120/crash-2020-11-01_17.54.40-client.txt)

**Comment by mxnmnm** [comment]
Having a similar issue but it just gives me an error in the log and doesn't crash

https://gist.github.com/mxnmnm/0d442ad5417db5ecba4002427a17d92a

**Comment by supermassimo** [comment]
This should be fixed after updating to Dynamic Trees 0.9.20
Thanks for your patience :)

**Comment by P3rf3ctXZer0** [comment]
Awesome glad some devs still fix bugs :D I know 1.12.2 is on its way out but its still here for at least another 3 months or more.
Less than 12 though.

**Comment by P3rf3ctXZer0** [comment]
fixed - thanks for efforts :D
