### ISSUE TITLE
Dynamic IC2 Rubber Trees crash the game when tapped (1.12.2)

### ISSUE THREAD

**Issue by UlticraftMTT** [supermassimo/DynamicTrees-ExC#54]
Don't know how to tag issues, i'm new to using Github, but i wanted to make this crash report.

Anyway, Dynamic IC2 Rubber Trees can't be tapped of sticky resin, doing so crashes the game. I actually took the addon out of my private modpack because of it.

Crash Report: https://pastebin.com/9ASTqgGh

**Comment by Harleyoc1** [comment]
It's calling a method that must've been removed recently. I'll take a look at it now. You could try downgrading industrial craft to an older version for the time being.

[Update] I think I've found the actual issue, ignore the above. I believe the sound is being called server-side which is obviously throwing an error.

**Comment by Harleyoc1** [comment]
The below patch should solve your issue. As I was unable to recreate this issue do you mind testing it out?

[DynamicTreesIC2-1.12.2-1.2.1-SNAPSHOT.jar.zip](https://github.com/supermassimo/DynamicTrees-ExC/files/5504853/DynamicTreesIC2-1.12.2-1.2.1-SNAPSHOT.jar.zip)

**Comment by Shumbalion** [comment]
I think I’m having the exact same issue tapping rubber trees = crash.

_The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: ic2.core.audio.AudioManager.playOnce(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/String;ZF)V
Exit Code: -1_

Sadly the patch didn’t appear to fix it for me, though I am happy to help with testing as well.

--

Unrelated side note: Cos I’m not sure if it’s even a bug, rooty dirt after chopping trees is turned into a grass block. I’ve only used this mod in RLcraft before and I’m pretty sure the rooty dirt remained. So just pointing out the difference in behaviour, I’m new to modded MC.

**Comment by ShiroBlank** [comment]
I'm also having the same issue as OP exact same errors.

Patch didn't work.

**Comment by Harleyoc1** [comment]
Weird. Just a strange issue as a I can’t manage to recreate it even using the same versions you were. Perhaps another mod you’re using is interfering, have you tried it with just IC2, DT and DT for IC2 installed?

**Comment by Shumbalion** [comment]
Was about to starts testing 1 by 1 but…. 
Can confirm crash with just 3 mods.

https://pastebin.com/ycZK4auE
DynamicTrees-1.12.2-0.9.20.jar
industrialcraft-2-2.8.221-ex112.jar
DynamicTreesIC2-1.12.2-1.2.0.jar

https://pastebin.com/KV1LFNUt
DynamicTrees-1.12.2-0.9.20.jar
industrialcraft-2-2.8.221-ex112.jar
DynamicTreesIC2-1.12.2-1.2.1-SNAPSHOT.jar

**Comment by democat3457** [comment]
Seems as if the game is treating the `PositionSpec` enum as an `Object` for some odd reason and can't find the method with the `Object`-ified enum.

**Comment by supermassimo** [comment]
[DynamicTreesIC2-1.12.2-1.2.1-SNAPSHOT_3.jar.zip](https://github.com/supermassimo/DynamicTrees-ExC/files/5526705/DynamicTreesIC2-1.12.2-1.2.1-SNAPSHOT_3.jar.zip)

Please try this patch

EDIT: updated to a new patch, try this one

EDIT 2: already got someone to test, thanks!

**Comment by supermassimo** [comment]
Fixed in [1.2.1](https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-industrial-craft-2/files/3108980)
