### ISSUE TITLE
(Suggestion) Add Forestry and Plants Compatitbility

### ISSUE THREAD

**Issue by MrProton657** [supermassimo/DynamicTrees-ExC#6]
If you have time an interest it would be great if you add Forestry and Plants Compat.

**Comment by supermassimo** [comment]
Forestry is planned and in the works, please check the Projects tab.

**Comment by leonbaronick** [comment]
Do you also consider adding compat for the extra trees addon (Binnie's mods)?

**Comment by supermassimo** [comment]
@Zerrox0 please make a separate post for new suggestions

**Comment by leonbaronick** [comment]
Thought it belonged here, since extra trees is just a forestry addon, but I'll create one if you want
