### ISSUE TITLE
No inicia el juego en la 1.16.4

### ISSUE THREAD

**Issue by d-rick** [supermassimo/DynamicTrees-ExC#63]
El juego no inicia al ejecutar el mod "Dynamic Trees - Quark" en la version 1.16.4 de Minecraft

**Comment by supermassimo** [comment]
por favor incluye una archivo .log para poder hacer algo al respecto. "hola no sirve" no me ayuda

**Comment by d-rick** [comment]
lo siento mi error.
te dejo el crash report

[crash-2021-05-05_15.08.42-fml.txt](https://github.com/supermassimo/DynamicTrees-ExC/files/6430001/crash-2021-05-05_15.08.42-fml.txt)

![dynamic quark crash](https://user-images.githubusercontent.com/83624925/117203248-6844f400-adb4-11eb-98b5-2643beb95d4f.PNG)

**Comment by Harleyoc1** [comment]
@supermassimo DT's `mods.toml` allows 1.16.4 so the add-ons probably should too. There's no reason not to given how little changed between the versions (pretty sure it is a few lines or something like that).

**Comment by supermassimo** [comment]
Yup, was my mistake.
@d-rick mala mia, ya lo arreglo y saco una actualización para DTQuark

**Comment by supermassimo** [comment]
Fixed in [DTQuark 2.0.2](https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-quark/files/3299989)

**Comment by d-rick** [comment]
sigue sin funcionar y me da el mismo error, la versión de forge debe ser **1.16.4 - 35.1.37** para que funcione en la 1
.16.4
[crash-2021-05-05_21.18.51-fml.txt](https://github.com/supermassimo/DynamicTrees-ExC/files/6431345/crash-2021-05-05_21.18.51-fml.txt)

**Comment by Harleyoc1** [comment]
Looks like you forgot to enable connections to FML >= 35 Max.

**Comment by supermassimo** [comment]
Aaaaa

**Comment by supermassimo** [comment]
Fixed in [DTQuark - 2.0.3](https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-quark/files/3300417)
