### ISSUE TITLE
Alex's mobs dynamic trees integration

### ISSUE THREAD

**Issue by Beam196** [supermassimo/DynamicTrees-ExC#64]
could you make dynamic tree's alex's mobs support addon to support banana item and it drop from only jungle leaves block which your jungle tree isn't has #drops_bananas tag plz

**Comment by supermassimo** [comment]
you can do that yourself with a datapack

**Comment by Beam196** [comment]
I don't know datapack code I just want a banana tree from alex's mobs

**Comment by Beam196** [comment]
> you can do that yourself with a datapack
I don't know datapack I just want a banana tree from alex's mobs
