### ISSUE TITLE
Alex's mobs dynamic trees intergration

### ISSUE THREAD

**Issue by Beam196** [supermassimo/DynamicTrees-ExC#66]
could you make dynamic tree's alex's mobs support addon to support banana item and it drop from only jungle leaves block which your jungle tree isn't has #drops_bananas tag so I want dynamic banana trees similar to vanilla apple trees plz

ps.sorry for comment this again my last comment has misunderstanding
`1.16.5`

**Comment by Beam196** [comment]
- [1.16.5 ]

**Comment by Beam196** [comment]
> could you make dynamic tree's alex's mobs support addon to support banana item and it drop from only jungle leaves block which your jungle tree isn't has #drops_bananas tag so I want dynamic banana trees similar to vanilla apple trees plz
> 
> ps.sorry for comment this again my last comment has misunderstanding

**Comment by Beam196** [comment]
#1.16.5

**Comment by Harleyoc1** [comment]
Has been added to the list on #59.

**Comment by Harleyoc1** [comment]
Due to DT using a custom drop system I doubt adding the tag alone would work. You'll have to wait for customisable drop creators in tree packs which I'm working on right now, or for a compatibility mod.
