### ISSUE TITLE
[Dt Quark] Seeds can't be planted on turf

### ISSUE THREAD

**Issue by WenXin20** [supermassimo/DynamicTrees-ExC#80]
`Minecraft v1.16.5`
`Forge v36.2.4`
`Dt Quark v2.1.0`

I've noticed that currently Quark's Turf block is missing from the `soil_properties` folder. 
Saplings can also be planted on turf stairs if the `half` blockstate is set to `top` and on turf slabs if the `type` blockstate is set to `top` or `double`, and vertical turf slabs if the type is `double`. Though not sure if soils can consider blockstates.

Also noticed that rooty glowcelium doesn't produce particles, although thats pretty minor.

data & blockstate for turf:
[turf.zip](https://github.com/supermassimo/DynamicTrees-ExC/files/7356075/turf.zip)

**Comment by Harleyoc1** [comment]
Adding support for planting on the turf stairs/slabs should be possible but will require custom `RootyBlock` implementations. We could potentially add these to base DT since it seems inevitable some other mods will also require this functionality.

**Comment by supermassimo** [comment]
Added turf support on [DT-Quark 2.1.1](https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-quark/files/3554615)
Support for slab and stair turf blocks will be implemented in the future.
