### ISSUE TITLE
[Dt Atum] Rooty Tilled Fertile Soil has a missing texture

### ISSUE THREAD

**Issue by WenXin20** [supermassimo/DynamicTrees-ExC#81]
`Minecraft v1.16.5`
`Forge v36.2.4`
`Dt Atum v1.1.1`

When a seed is planted on Tilled Fertile Soil from Atum, the rooty soil has a missing texture instead of becoming Fertile Soil.

![2021-10-15_17 42 42](https://user-images.githubusercontent.com/12000593/137562196-a373679c-7c62-4065-a804-8b7b68ce18d9.png)

**Comment by supermassimo** [comment]
This should be fixed in the next patch for Dynamic Trees
