### ISSUE TITLE
[DT BOP] Hellbark log disconnected

### ISSUE THREAD

**Issue by WenXin20** [supermassimo/DynamicTrees-ExC#83]
`Minecraft v1.16.5`
`Forge v36.2.4`
`Dt BOP v2.0.6`

The log on the hellbark tree doesn't seem to connect to the leaves physically or visually until chopped down, which looks quite odd.

![2021-10-16_12 25 08](https://user-images.githubusercontent.com/12000593/137944553-79963dc8-308c-4218-ab98-500774d9d576.png)

**Comment by Harleyoc1** [comment]
DT BOP is on its own repository, please re-open this [here](https://github.com/the-realest-stu/DynamicTrees-BOP/issues).

**Comment by WenXin20** [comment]
Ah, thanks
